### ISSUE TITLE
Replace the HTML drawing with SVG

### ISSUE THREAD

**Issue by djalilhebal** [djalilhebal/softviz-semaphores#1]
Instead of drawing with HTML and CSS (`display: flex` and `order: <calculatedPosition>`), use SVG and set 'calculatedPosition' manually using CSS `translate(x, y)`

- [ ] Recreate the 'scene' with SVG
  - [x] Basic layout: `images/scene.svg`
  - [ ] Dynamic elements (the first comment shows a possible approach)
  - [x] Add `transform: translate` animations (see the broken code below)

- [x] CSS: Use only cheaply animated props, like `opacity` and `transform translate`

- [ ] CSS: Use cubic-bezier easing to create more natural car movements
  - Try https://cubic-bezier.com/

---

```js
$elem.style.setProperty("--position", index + 1);
```

```css
[data-state] {
  transform: translate(calc(var(--position) * var(--delta-x) * 1vw), 10px);
}

[data-direction="west"] {
  --delta-x: 50;
  --delta-y: 0;
}

[data-direction="south"] {
  --delta-x: 45;
  --delta-y: 0;
}

[data-state="new"] {
  opacity: 0;
}

[data-state="leave"] {
  opacity: 1;
  animation: 5s leaving infinite;
}

/*
.sim[data-state="running"] .vehicle[data-state=leave] {
  animate leaving!
}

.sim[data-state="collision"] #crash-area {
  opacity: 1;
}
*/

@keyframes leaving {
  50% {
    opacity: 1;
    transform: translate(calc(var(--delta-x) * 2vw), -40px);
  }

  100% {
    opacity: 0;
    transform: translate(calc(var(--delta-x) * 10vw), calc(var(--delta-y) * 10vw));
  }
}
```
